services:
  mongo:
    image: mongo:4.4
    ports:
      - "127.0.0.1:27017:27017"
    command: --nojournal
    volumes: 
      - mongo-data:/data/db
    restart: "no"

  orion:
    image: fiware/orion:3.10.1
    links: 
      - mongo
    ports:
      - "127.0.0.1:1026:1026"
    command: -dbhost mongo
    depends_on:
      - mongo
    restart: "no"
    
volumes:
  mongo-data:
    driver: local

